#!/usr/bin/env bash

mapfile nouns < ./nouns.txt
mapfile adjectives < ./adjectives.txt

nounIndex=$RANDOM%$((${#nouns[@]}-1))

adjectiveIndex=$RANDOM%$((${#adjectives[@]}-1))

adjective="$(echo -e "${adjectives[$adjectiveIndex]}" | tr -d '[:space:]')"
noun="$(echo -e "${nouns[$nounIndex]}" | tr -d '[:space:]')"

echo $adjective-$noun
